version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=musamin_app
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - storage:/var/www/storage
      - bootstrap_cache:/var/www/bootstrap/cache

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musamin_app
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  storage:
  bootstrap_cache: