version: '3.8'

x-app-environment: &app-environment
  - APP_ENV=production
  - APP_DEBUG=false
  - APP_KEY=base64:ioxbXKw7LniLXzvrK7aTPulZ4XtlLx2mbcmyGo50CjA=
  - APP_URL=https://musamin.app
  - DB_CONNECTION=mysql
  - DB_HOST=mysql
  - DB_PORT=3306
  - DB_DATABASE=default
  - DB_USERNAME=mysql
  - DB_PASSWORD=Musamin@70
  - N8N_API_KEY=n8n_secure_key_2025_musamin_app_integration
  - QUEUE_CONNECTION=database

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment: *app-environment
    depends_on:
      - mysql
    networks:
      - app-network

  scheduler:
    build: .
    command: php artisan schedule:work
    environment: *app-environment
    depends_on:
      - mysql
    networks:
      - app-network

  queue:
    build: .
    command: php artisan queue:work --sleep=3 --tries=3
    environment: *app-environment
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=Musamin@70
      - MYSQL_DATABASE=default
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=Musamin@70
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local